CREATE TABLE users
(
    id       int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email    varchar NOT NULL,
    password varchar NOT NULL,
    role     varchar NOT NULL
);

CREATE TABLE tasks
(
    id           int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title        varchar NOT NULL,
    description  varchar NOT NULL,
    status       varchar NOT NULL,
    priority     varchar NOT NULL,
    author_id    int REFERENCES users (id) ON DELETE CASCADE,
    performer_id int REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE comments
(
    id        int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    author_id int REFERENCES users (id) ON DELETE CASCADE,
    task_id   int REFERENCES tasks (id) ON DELETE CASCADE,
    message   varchar NOT NULL
);
